In [1]:
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.float_format', '{:,.0f}'.format)

In [2]:
gl=pd.read_csv("gl_clean.csv", parse_dates=['posting_date'])

In [4]:
coa = pd.read_csv("coa_clean.csv")

In [5]:
gl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2183 entries, 0 to 2182
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   journal_id            2183 non-null   object
 1   posting_date          2183 non-null   datetime64[ns]
 2   account_no            2183 non-null   int64
 3   cost_center           2183 non-null   object
 4   amount                2183 non-null   float64
 5   currency              2183 non-null   object
 6   vendor                1448 non-null   object
 7   description           2183 non-null   object
 8   flag_unknown_account  2183 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 138.7+ KB

In [6]:
df=gl.merge(coa,on='account_no',how='left')

In [7]:
df.head()

,journal_id,posting_date,account_no,cost_center,amount,currency,vendor,description,flag_unknown_account,account_name,account_group,statement
0,JE101094,2025-01-03,4000,CC100,"11,407",EUR,NaN,Revenue - Machine Sales Jan 2025,False,Revenue - Machine Sales,Revenue,P&L
1,JE102157,2025-12-11,6400,CC300,"-19,411",EUR,Google Ireland Ltd,Marketing & Advertising Dec 2025,False,Marketing & Advertising,OPEX,P&L
2,JE100821,2024-09-07,6700,CC600,"-1,267",EUR,KPMG AG,Consulting & Legal Sep 2024,False,Consulting & Legal,OPEX,P&L
3,JE101506,2025-05-08,6100,CC200,"-14,210",EUR,NaN,Social Security Contributions May 2025,False,Social Security Contributions,Personnel,P&L
4,JE100443,2024-05-23,6300,CC200,"-1,368",EUR,Vattenfall Europe,Utilities May 2024,False,Utilities,OPEX,P&L

In [8]:
df['account_group'].isna().sum()

np.int64(8)

In [10]:
df['account_group']=df['account_group'].fillna('Unmapped')

In [21]:
df[df['account_group'] == "Unmapped"]

,journal_id,posting_date,account_no,cost_center,amount,currency,vendor,description,flag_unknown_account,account_name,account_group,statement
372,JE100834,2024-09-07,6450,CC500,-673,EUR,Commerzbank AG,Interest Expense Sep 2024,True,NaN,Unmapped,NaN
635,JE101502,2025-05-20,6450,CC500,"-23,084",EUR,Hays AG,Salaries May 2025,True,NaN,Unmapped,NaN
683,JE101489,2025-05-20,6450,CC110,"-1,516",EUR,NaN,Sales Discounts May 2025,True,NaN,Unmapped,NaN
1185,JE101190,2025-02-24,6450,CC100,"91,498",EUR,NaN,Revenue - Machine Sales Feb 2025,True,NaN,Unmapped,NaN
1330,JE100473,2024-05-20,6450,CC500,"-1,667",EUR,Commerzbank AG,Interest Expense May 2024,True,NaN,Unmapped,NaN
1431,JE102153,2025-12-01,6450,CC200,-171,EUR,Vattenfall Europe,Utilities Dec 2025,True,NaN,Unmapped,NaN
1539,JE100601,2024-07-18,6450,CC300,"-17,084",EUR,Hays AG,Salaries Jul 2024,True,NaN,Unmapped,NaN
2100,JE100696,2024-08-25,6450,CC100,"-6,494",EUR,NaN,Social Security Contributions Aug 2024,True,NaN,Unmapped,NaN

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2183 entries, 0 to 2182
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   journal_id            2183 non-null   object
 1   posting_date          2183 non-null   datetime64[ns]
 2   account_no            2183 non-null   int64
 3   cost_center           2183 non-null   object
 4   amount                2183 non-null   float64
 5   currency              2183 non-null   object
 6   vendor                1448 non-null   object
 7   description           2183 non-null   object
 8   flag_unknown_account  2183 non-null   bool
 9   account_name          2175 non-null   object
 10  account_group         2183 non-null   object
 11  statement             2175 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(8)
memory usage: 189.9+ KB

In [23]:
df['year']=df['posting_date'].dt.year

In [24]:
df.head(3)

,journal_id,posting_date,account_no,cost_center,amount,currency,vendor,description,flag_unknown_account,account_name,account_group,statement,year
0,JE101094,2025-01-03,4000,CC100,"11,407",EUR,NaN,Revenue - Machine Sales Jan 2025,False,Revenue - Machine Sales,Revenue,P&L,2025
1,JE102157,2025-12-11,6400,CC300,"-19,411",EUR,Google Ireland Ltd,Marketing & Advertising Dec 2025,False,Marketing & Advertising,OPEX,P&L,2025
2,JE100821,2024-09-07,6700,CC600,"-1,267",EUR,KPMG AG,Consulting & Legal Sep 2024,False,Consulting & Legal,OPEX,P&L,2024

In [25]:
df['Month']=df['posting_date'].dt.month

In [26]:
df.head(3)

,journal_id,posting_date,account_no,cost_center,amount,currency,vendor,description,flag_unknown_account,account_name,account_group,statement,year,Month
0,JE101094,2025-01-03,4000,CC100,"11,407",EUR,NaN,Revenue - Machine Sales Jan 2025,False,Revenue - Machine Sales,Revenue,P&L,2025,1
1,JE102157,2025-12-11,6400,CC300,"-19,411",EUR,Google Ireland Ltd,Marketing & Advertising Dec 2025,False,Marketing & Advertising,OPEX,P&L,2025,12
2,JE100821,2024-09-07,6700,CC600,"-1,267",EUR,KPMG AG,Consulting & Legal Sep 2024,False,Consulting & Legal,OPEX,P&L,2024,9

In [28]:
df[['posting_date', 'year', 'Month']].head()

  posting_date  year  Month
0   2025-01-03  2025      1
1   2025-12-11  2025     12
2   2024-09-07  2024      9
3   2025-05-08  2025      5
4   2024-05-23  2024      5

In [29]:
pnl = df.pivot_table(index='account_group', columns='year', values='amount', aggfunc='sum')
pnl

year                2024       2025
account_group
COGS          -4,649,370 -5,241,210
Financial        -70,126    -75,704
OPEX          -1,747,781 -1,996,973
Personnel     -3,231,235 -3,508,479
Revenue       10,925,234 11,367,596
Unmapped         -25,918     66,727

In [30]:
revenue = pnl.loc['Revenue']

In [31]:
revenue

year
2024   10,925,234
2025   11,367,596
Name: Revenue, dtype: float64

In [32]:
###cogs is cost of goods
gross_profit = revenue + pnl.loc['COGS']

In [33]:
gross_profit

year
2024   6,275,864
2025   6,126,386
dtype: float64

In [34]:
##earning before interest and taxes
ebit = gross_profit + pnl.loc['Personnel'] + pnl.loc['OPEX']
ebit

year
2024   1,296,848
2025     620,934
dtype: float64

In [35]:
gross_margin = gross_profit / revenue * 100
ebit_margin = ebit / revenue * 100

In [38]:
summary = pd.DataFrame({'Revenue': revenue, 'Gross Profit': gross_profit, 'Gross Margin %': gross_margin, 'EBIT': ebit, 'EBIT Margin %': ebit_margin})
summary

        Revenue  Gross Profit  Gross Margin %      EBIT  EBIT Margin %
year
2024 10,925,234     6,275,864              57 1,296,848             12
2025 11,367,596     6,126,386              54   620,934              5

In [40]:
# ### Finding 1: Profit halved despite higher sales
# - Revenue grew 4% (€10.9M → €11.4M)
# - But EBIT fell 52% (€1.30M → €0.62M); the EBIT margin dropped from 12% to 5%
# - Gross margin fell from 57% to 54%, so material costs (COGS) grew faster than sales (+13%)
# - OPEX also grew 14%
# - Next question: which costs exactly? → Budget vs Actual analysis

In [41]:
summary.to_csv("pnl_summary.csv")

In [2]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\dell\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\dell\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [9]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("YOUR_MYSQL_PASSWORD")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/nordwerk")

In [10]:
inv = pd.read_csv("invoices_clean.csv", parse_dates=['invoice_date', 'due_date', 'payment_date'])
inv.to_sql('invoices', engine, if_exists='replace', index=False)
print(len(inv), "rows loaded")

900 rows loaded

In [11]:
cust = pd.read_csv("customers_clean.csv")
cust.to_sql('customers', engine, if_exists='replace', index=False)
print(len(cust), "rows loaded")

25 rows loaded